services:
  postgres:
    image: postgres:16-alpine
    container_name: notifyme-postgres
    environment:
      POSTGRES_USER: notifyme
      POSTGRES_PASSWORD: notifyme_dev_only
      POSTGRES_DB: notifyme
    ports:
      - "5432:5432"
    volumes:
      - notifyme-postgres-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: notifyme-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  notifyme-postgres-data:
