// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyMe.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotifyMe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotifyMeDbContext))]
    [Migration("20260922084212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotifyMe.Domain.Alerts.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("NotifyMe.Domain.Channels.ChannelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("channel_configs", (string)null);
                });

            modelBuilder.Entity("NotifyMe.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("NormalizedEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("Status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NotifyMe.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("NotifyMe.Domain.Alerts.AlertRule", b =>
                {
                    b.OwnsOne("NotifyMe.Domain.Alerts.MatchCriteria", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("AlertRuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Keywords")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("keywords");

                            b1.Property<string>("MinimumSeverity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("minimum_severity");

                            b1.HasKey("AlertRuleId");

                            b1.ToTable("alert_rules");

                            b1.WithOwner()
                                .HasForeignKey("AlertRuleId");
                        });

                    b.Navigation("Criteria")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
